# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
twitter_username: 

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock

# Welcome to Jekyll!
#
# Site settings
title: Kelly McCarthy
description:  "I bring people &amp; technology together."
owner: Kelly McCarthy
first_published: 2017 # if migrating another site, the year of your first publish
email: kelly@easy-designs.net
social:
  twitter: https://twitter.com/ShirleyTemper
  linkedin-square: https://www.linkedin.com/in/kcmccarthy1/
  facebook-official: https://www.facebook.com/kellycorinnemccarthy
  google-plus-square: https://plus.google.com/106692421955616846961
  instagram: https://www.instagram.com/kellymccarthy/

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kelly-mccarthy.com" # the base hostname & protocol for your site, e.g. http://example.com

# SASS
sass:
    sass_dir: _scss
    #style: compressed
    sourcemap: true